resources:
  App\Entity\Doctors:
    itemOperations:
      get:
        method: get
        path: /doctor/{id}
        controller: App\Controller\DoctorsItemController
        openapi_context:
          summary: Konkrétny lekár
          description: |
            Tento endpoint poskytuje detailné informácie o konkrétnom lekárovi.
          parameters:
            - in: path
              name: id
              description: ID lekára
              schema:
                type: integer
              required: true
          requestBody:
          responses:
            '200':
              description: Výsledky vyhľadávania
              content:
                application/json:
                  schema:
                    type: object
                    required:
                      - name
                      - surname
                      - email
                      - specialisation
                      - appointments_length
                      - address
                      - city
                      - description
                    properties:
                      id:
                        type: integer
                        example: 13
                      name:
                        type: string
                        example: Peter
                        maxLength: 64
                      surname:
                        type: string
                        example: Slovák
                        maxLength: 64
                      title:
                        type: string
                        example: MUDr.
                        maxLength: 8
                      email:
                        type: string
                        format: email
                        example: peter.slovak@gmail.com
                        maxLength: 256
                      phone:
                        type: string
                        example: +421 901 234 567
                        minLength: 10
                        maxLength: 16
                      specialisation:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 13
                          title:
                            type: string
                            example: Ortopéd
                      appointments_length:
                        type: integer
                        example: 30
                        description: Dĺžka jedného vyšetrenia v minútach
                      address:
                        type: string
                        example: Hlboká 32
                        maxLength: 128
                      city:
                        type: string
                        example: Bratislava II
                        maxLength: 128
                      description:
                        type: string
                        example: >-
                          Pôsobí ako všeobecná zubná lekárka pre deti aj dospelých. Vykonáva aj
                          endodontické vyšetrenia.
                      schedules:
                        type: array
                        items:
                          type: object
                          required:
                            - weekday
                            - time_from
                            - time_to
                          properties:
                            weekday:
                              type: integer
                              example: 3
                              minimum: 0
                              maximum: 6
                            time_from:
                              type: string
                              format: time
                              example: '09:00'
                            time_to:
                              type: string
                              format: time
                              example: '13:00'
                      is_favorite:
                        type: boolean
                        default: false
            '404':
              description: Lekára sa nepodarilo nájsť
      avatar:
        method: get
        path: /doctor/{id}/avatar
        controller: App\Controller\DoctorAvatarController
        openapi_context:
          summary: Avatar lekára
          description: |
            Tento endpoint poskytuje fotografiu vybraného lekára.
          parameters:
            - in: path
              name: id
              description: ID lekára
              schema:
                type: integer
              required: true
          responses:
            '200':
              description: OK
              content:
                image/*:
                  schema:
                    type: string
                    format: binary
            '404':
              description: Lekára sa nepodarilo nájsť
      removeFavorite:
        method: delete
        path: /doctor/{id}/favorite
        controller: App\Controller\DoctorFavoriteRemoveController
        openapi_context:
          summary: Odstránenie lekára z obľúbených
          description: |
            Pomocou tohto endpointu si vie prihlásený pacient odstrániť lekára zo
            zoznamu obľúbených lekárov.
          parameters:
            - in: path
              name: id
              description: ID lekára
              schema:
                type: integer
              required: true
          responses:
            '204':
              description: Lekár bol odobraný
            '401':
              description: Chýbajúca autentifikácia
            '403':
              description: Nedostatočné práva
            '404':
              description: Lekára sa nepodarilo nájsť
    collectionOperations:
      addFavorite:
        method: post
        path: /doctor/{id}/favorite
        controller: App\Controller\DoctorFavoriteAddController
        openapi_context:
          summary: Pridanie lekára ako obľúbeného
          description: |
            Pomocou tohto endpointu si vie prihlásený pacient priradiť nového lekára
            do zoznamu svojich obľúbených lekárov.
          parameters:
            - in: path
              name: id
              description: ID lekára
              schema:
                type: integer
              required: true
          requestBody:
            content:
              application/json:
                schema:
                  type: object
          responses:
            '204':
              description: Lekár bol pridaný
            '401':
              description: Chýbajúca autentifikácia
            '403':
              description: Nedostatočné práva
            '404':
              description: Lekára sa nepodarilo nájsť
      get:
        method: get
        path: /doctors
        controller: App\Controller\DoctorsCollectionController
        openapi_context:
          summary: Zoznam lekárov
          description: |
            Zoznam všetkých lekárov s možnosťou filtrovania pomocou parametrov,
            napríklad full-textové vyhľadávanie nad menom lekára, filtrovanie podľa
            špecializácie, alebo v prípade prihláseného používateľa s možnosťou
            vyfiltrovania svojich obľúbených lekárov.
          parameters:
            - in: query
              name: name
              description: Vyhľadávanie podľa mena lekára
              schema:
                type: string
              required: false
            - in: query
              name: specialisation
              description: Vyhľadávanie podľa ID špecializácie
              schema:
                type: integer
              required: false
            - in: query
              name: city
              description: Vyhľadávanie podľa mesta
              schema:
                type: string
              required: false
            - in: query
              name: only_favorites
              description: Zobraziť iba obľúbených lekárov
              schema:
                type: boolean
              required: false
            - in: query
              name: page
              description: Číslo strany
              schema:
                type: integer
                default: 1
              required: false
            - in: query
              name: per_page
              description: Počet výsledkov na jednu stranu
              schema:
                type: integer
                default: 10
              required: false
          responses:
            '200':
              description: Výsledky vyhľadávania
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      required:
                        - name
                        - surname
                        - email
                        - specialisation
                        - appointments_length
                        - address
                        - city
                        - description
                      properties:
                        id:
                          type: integer
                          example: 13
                        name:
                          type: string
                          example: Peter
                          maxLength: 64
                        surname:
                          type: string
                          example: Slovák
                          maxLength: 64
                        title:
                          type: string
                          example: MUDr.
                          maxLength: 8
                        email:
                          type: string
                          format: email
                          example: peter.slovak@gmail.com
                          maxLength: 256
                        phone:
                          type: string
                          example: +421 901 234 567
                          minLength: 10
                          maxLength: 16
                        specialisation:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 13
                            title:
                              type: string
                              example: Ortopéd
                        appointments_length:
                          type: integer
                          example: 30
                          description: Dĺžka jedného vyšetrenia v minútach
                        address:
                          type: string
                          example: Hlboká 32
                          maxLength: 128
                        city:
                          type: string
                          example: Bratislava II
                          maxLength: 128
                        description:
                          type: string
                          example: >-
                            Pôsobí ako všeobecný zubný lekár pre deti aj dospelých. Vykonáva aj 
                            endodontické vyšetrenia.
                        is_favorite:
                          type: boolean
                          default: false